services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: shortest-route-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_PATH: /app/data/delivery.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped